sudo: required

dist: trusty

before_install: 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get install mono-complete mono-devel
  - wget -O os.deb http://oscript.io/downloads/night-build/deb
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript
  - curl -L https://github.com/asosnoviy/1testrunner/releases/download/1.7.1-alpha/1testrunner-1.7.1_alpha.ospx > 1testrunner.ospx


install: 
  - sudo opm install
  - sudo opm install -f ./1testrunner.ospx

script:
  - opm test